spring.application.name=CraftLanka-Project

#database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Craftlanka?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

#spring.jpa.hibernate.ddl-auto=update

#JPA configuration
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#jwt configurations
jwt.expiration=864000000
jwt.secretKey=mysecrty3424WEe32fmysecrty3424WEe32fmysecrty3424WEe32fmysecrty3424WEe32f

#Payhere Configuration
payhere.merchant.id=1234795
payhere.secret=MTIzNzE5MDU5ODQ1MTU3MDAyODE2MDE5NzI5NzE0MjI4MDc2ODky
payhere.url=https://sandbox.payhere.lk/pay/checkout

 # test card number = 4916217501611292
#  test cvc = 123
# test date = 12/30