package lk.ijse.javafx.craftlankaproject.service.impl;

import jakarta.persistence.EntityExistsException;
import lk.ijse.javafx.craftlankaproject.dto.CraftProductDtO;
import lk.ijse.javafx.craftlankaproject.entity.CraftProduct;
import lk.ijse.javafx.craftlankaproject.repository.CraftProductRepository;
import lk.ijse.javafx.craftlankaproject.repository.UserRepository;
import lk.ijse.javafx.craftlankaproject.service.CraftProductService;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class CraftProductServiceImpl implements CraftProductService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CraftProductRepository craftProductRepository;

    @Autowired
    private ModelMapper modelMapper;

    @Override
    public CraftProduct addProduct(CraftProductDtO craftProductDtO) {
        // Map DTO to Entity
        CraftProduct product = modelMapper.map(craftProductDtO, CraftProduct.class);

        // Logic check: If ID is provided, check if it already exists
        if (craftProductDtO.getId() != null) {
            if (craftProductRepository.existsById(craftProductDtO.getId())) {
                throw new EntityExistsException("Product already exists!");
            }
        }

        // Save the product (ID will be auto-generated by MySQL)
        return craftProductRepository.save(product);
    }

    @Override
    public CraftProduct updateProduct(Long id, CraftProductDtO craftProductDtO) {

        Optional<CraftProduct> productOptional = craftProductRepository.findById(id);

        if (productOptional.isPresent()) {

            CraftProduct product = modelMapper.map(craftProductDtO, CraftProduct.class);
            product.setId(id);

            return craftProductRepository.save(product);

        } else {

            throw new NullPointerException("Product not available");
        }
    }

    public void deleteProductById(Long id) {
        if (craftProductRepository.existsById(id)) {
            craftProductRepository.deleteById(id);
        } else {
            throw new NullPointerException("Product not available to delete");
        }
    }

    @Override
    public List<CraftProductDtO> getAllProducts() {

        List<CraftProductDtO> productDTOList = new ArrayList<>();

        List<CraftProduct> productList = craftProductRepository.findAll();

        for (int i = 0; i < productList.size(); i++) {

            CraftProductDtO dto =
                    modelMapper.map(productList.get(i), CraftProductDtO.class);

            productDTOList.add(dto);
        }

        if (productDTOList.isEmpty()) {

            throw new NullPointerException("Products are not available yet");
        }

        return productDTOList;
    }
}